### ISSUE TITLE
Upgrade to discord.js 12

### ISSUE THREAD

**Issue by FrBillyD** [An-Idiots-Guide/guidebot#103]
Hello,
Is the transition to discord.js version 12 planned ?
We're starting to hear about it, but the changes seem significant...

Thank you !

**Comment by eslachance** [comment]
There are currently no plans to update all our code to discord.js version 11. Some of it might be, but there's no garantee, since v12 is, as you say, a very large breaking update, and most of those changes are conceptual in nature and offer no benefits. We're mostly staying on v11 ourselves anyways for the time being.

**Comment by FrBillyD** [comment]
Ok good. This is what I was thinking about. Thanks !
