### ISSUE TITLE
This is not a issue. More of a question of understanding.

### ISSUE THREAD

**Issue by KainesLaw** [An-Idiots-Guide/guidebot#137]
So when I change a command setting to `enabled: true` to `enabled: false`, I still can use the command. Or do I bypass it since I am the owner? 

2. What does GuildOnly mean?

Sorry for the trouble. I am new to having all these new features in command handlers.

**Comment by Chicken** [comment]
Seems like `enabled` is broken (not utilised at all by the command handler?). GuildOnly means that the command can only be used in servers and not in DMs.

**Comment by KainesLaw** [comment]
> Seems like `enabled` is broken (not utilised at all by the command handler?). GuildOnly means that the command can only be used in servers and not in DMs.

Ah that's a shame that it's broken.

**Comment by YorkAARGH** [comment]
Unfortunately it's a relic of an old version of guidebot, we intended to implement this feature but we didn't know _HOW_ to do it, it's remained in the code for the hopeful time we do add the functionality.

**Comment by YorkAARGH** [comment]
~~Hey, I had to reopen this issue because I thought we didn't implement this yet. I looked through the code to see if we had or not and yeah we did actually implement this feature, and for all intents and purposes it fully works as [showed here in this screenshot](https://i.imgur.com/jJDHoxh.png).~~

~~The way the code is currently written, not even owners of the bot should be able to bypass this as shown in the code [here](https://github.com/AnIdiotsGuide/guidebot/blob/master/events/message.js#L46), and in the screenshot above I am listed as the bot owner and it still gave me the "disabled" message.~~

If you need support for this issue, you can drop by the server (link is at the top of the org page) for a more speedy support than here @KainesLaw.

Bah... stupid me... I shouldn't read/code first thing in the morning... disregard what I said LOL complete misunderstanding on my behalf... I'll certainly be looking into this a.s.a.p. now that I understand the issue at hand.

**Comment by YorkAARGH** [comment]
This has been fixed in the v13 update, which can be backported to v12.
